__version__ = "0.0.1"
# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_jacobian.ipynb.

# %% auto 0
__all__ = ['jacobian']

# %% ../nbs/00_jacobian.ipynb 3
def jacobian():
  print("running jacobian")
