__version__ = "0.0.1"
# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/99_core.ipynb.

# %% auto 0
__all__ = ['test']

# %% ../nbs/99_core.ipynb 2
from .jacob import jacobian

# %% ../nbs/99_core.ipynb 3
def test():
  print("testing")
