# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/javiche',
                'doc_host': 'https://Jan-David-Black.github.io',
                'git_url': 'https://github.com/Jan-David-Black/javiche',
                'lib_path': 'javiche'},
  'syms': { 'javiche.jacob': { 'javiche.jacob.jacobian': ('jacob.html#jacobian', 'javiche/jacob.py'),
                               'javiche.jacob.working': ('jacob.html#working', 'javiche/jacob.py')}}}
