# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/javiche',
                'doc_host': 'https://Jan-David-Black.github.io',
                'git_url': 'https://github.com/Jan-David-Black/javiche',
                'lib_path': 'javiche'},
  'syms': {}}
